/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
	'use strict';
	function supportsProperty(p) {
		var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
			i,
			div = document.createElement('div'),
			ret = p in div.style;
		if (!ret) {
			p = p.charAt(0).toUpperCase() + p.substr(1);
			for (i = 0; i < prefixes.length; i += 1) {
				ret = prefixes[i] + p in div.style;
				if (ret) {
					break;
				}
			}
		}
		return ret;
	}
	var icons;
	if (!supportsProperty('fontFeatureSettings')) {
		icons = {
			'home': '&#xe900;',
			'house': '&#xe900;',
			'home2': '&#xe901;',
			'house2': '&#xe901;',
			'home3': '&#xe902;',
			'house3': '&#xe902;',
			'newspaper': '&#xe904;',
			'news': '&#xe904;',
			'droplet': '&#xe90b;',
			'color2': '&#xe90b;',
			'play': '&#xe912;',
			'video': '&#xe912;',
			'film': '&#xe913;',
			'video2': '&#xe913;',
			'video-camera': '&#xe914;',
			'video3': '&#xe914;',
			'connection': '&#xe91b;',
			'wifi': '&#xe91b;',
			'podcast': '&#xe91c;',
			'broadcast': '&#xe91c;',
			'feed': '&#xe91d;',
			'wave': '&#xe91d;',
			'file-text': '&#xe922;',
			'file': '&#xe922;',
			'profile': '&#xe923;',
			'file2': '&#xe923;',
			'file-empty': '&#xe924;',
			'file3': '&#xe924;',
			'files-empty': '&#xe925;',
			'files': '&#xe925;',
			'file-text2': '&#xe926;',
			'file4': '&#xe926;',
			'file-picture': '&#xe927;',
			'file5': '&#xe927;',
			'file-music': '&#xe928;',
			'file6': '&#xe928;',
			'file-play': '&#xe929;',
			'file7': '&#xe929;',
			'file-video': '&#xe92a;',
			'file8': '&#xe92a;',
			'file-zip': '&#xe92b;',
			'file9': '&#xe92b;',
			'copy': '&#xe92c;',
			'duplicate': '&#xe92c;',
			'paste': '&#xe92d;',
			'clipboard-file': '&#xe92d;',
			'stack': '&#xe92e;',
			'layers': '&#xe92e;',
			'folder': '&#xe92f;',
			'directory': '&#xe92f;',
			'folder-open': '&#xe930;',
			'directory2': '&#xe930;',
			'folder-plus': '&#xe931;',
			'directory3': '&#xe931;',
			'folder-minus': '&#xe932;',
			'directory4': '&#xe932;',
			'folder-download': '&#xe933;',
			'directory5': '&#xe933;',
			'folder-upload': '&#xe934;',
			'directory6': '&#xe934;',
			'location': '&#xe947;',
			'map-marker': '&#xe947;',
			'location2': '&#xe948;',
			'map-marker2': '&#xe948;',
			'compass': '&#xe949;',
			'direction': '&#xe949;',
			'clock': '&#xe94e;',
			'time2': '&#xe94e;',
			'clock2': '&#xe94f;',
			'time3': '&#xe94f;',
			'display': '&#xe956;',
			'screen': '&#xe956;',
			'laptop': '&#xe957;',
			'computer': '&#xe957;',
			'mobile': '&#xe958;',
			'cell-phone': '&#xe958;',
			'mobile2': '&#xe959;',
			'cell-phone2': '&#xe959;',
			'tablet': '&#xe95a;',
			'mobile3': '&#xe95a;',
			'drawer': '&#xe95c;',
			'box': '&#xe95c;',
			'drawer2': '&#xe95d;',
			'box2': '&#xe95d;',
			'box-add': '&#xe95e;',
			'box3': '&#xe95e;',
			'box-remove': '&#xe95f;',
			'box4': '&#xe95f;',
			'download': '&#xe960;',
			'save': '&#xe960;',
			'upload': '&#xe961;',
			'load': '&#xe961;',
			'drive': '&#xe963;',
			'save3': '&#xe963;',
			'database': '&#xe964;',
			'db': '&#xe964;',
			'undo': '&#xe965;',
			'ccw': '&#xe965;',
			'redo': '&#xe966;',
			'cw': '&#xe966;',
			'undo2': '&#xe967;',
			'left': '&#xe967;',
			'redo2': '&#xe968;',
			'right': '&#xe968;',
			'forward': '&#xe969;',
			'right2': '&#xe969;',
			'reply': '&#xe96a;',
			'left2': '&#xe96a;',
			'user': '&#xe971;',
			'profile2': '&#xe971;',
			'users': '&#xe972;',
			'group': '&#xe972;',
			'user-check': '&#xe975;',
			'user4': '&#xe975;',
			'user-tie': '&#xe976;',
			'user5': '&#xe976;',
			'spinner6': '&#xe97f;',
			'loading7': '&#xe97f;',
			'spinner11': '&#xe984;',
			'loading12': '&#xe984;',
			'enlarge': '&#xe989;',
			'expand': '&#xe989;',
			'shrink': '&#xe98a;',
			'collapse': '&#xe98a;',
			'equalizer': '&#xe992;',
			'sliders': '&#xe992;',
			'equalizer2': '&#xe993;',
			'sliders2': '&#xe993;',
			'cog': '&#xe994;',
			'gear': '&#xe994;',
			'leaf': '&#xe9a4;',
			'nature': '&#xe9a4;',
			'power': '&#xe9b5;',
			'lightning': '&#xe9b5;',
			'switch': '&#xe9b6;',
			'list-numbered': '&#xe9b9;',
			'options': '&#xe9b9;',
			'list': '&#xe9ba;',
			'todo': '&#xe9ba;',
			'list2': '&#xe9bb;',
			'todo2': '&#xe9bb;',
			'cloud': '&#xe9c1;',
			'weather': '&#xe9c1;',
			'cloud-download': '&#xe9c2;',
			'cloud2': '&#xe9c2;',
			'cloud-upload': '&#xe9c3;',
			'cloud3': '&#xe9c3;',
			'cloud-check': '&#xe9c4;',
			'cloud4': '&#xe9c4;',
			'download2': '&#xe9c5;',
			'save4': '&#xe9c5;',
			'upload2': '&#xe9c6;',
			'load2': '&#xe9c6;',
			'download3': '&#xe9c7;',
			'save5': '&#xe9c7;',
			'upload3': '&#xe9c8;',
			'load3': '&#xe9c8;',
			'sphere': '&#xe9c9;',
			'globe': '&#xe9c9;',
			'earth': '&#xe9ca;',
			'globe2': '&#xe9ca;',
			'flag': '&#xe9cc;',
			'report': '&#xe9cc;',
			'eye': '&#xe9ce;',
			'views': '&#xe9ce;',
			'eye-blocked': '&#xe9d1;',
			'views4': '&#xe9d1;',
			'bookmark': '&#xe9d2;',
			'ribbon': '&#xe9d2;',
			'bookmarks': '&#xe9d3;',
			'ribbons': '&#xe9d3;',
			'sun': '&#xe9d4;',
			'weather2': '&#xe9d4;',
			'contrast': '&#xe9d5;',
			'brightness-contrast': '&#xe9d6;',
			'star-empty': '&#xe9d7;',
			'rate': '&#xe9d7;',
			'star-half': '&#xe9d8;',
			'rate2': '&#xe9d8;',
			'star-full': '&#xe9d9;',
			'rate3': '&#xe9d9;',
			'heart': '&#xe9da;',
			'like': '&#xe9da;',
			'heart-broken': '&#xe9db;',
			'heart2': '&#xe9db;',
			'warning': '&#xea07;',
			'sign': '&#xea07;',
			'notification': '&#xea08;',
			'warning2': '&#xea08;',
			'question': '&#xea09;',
			'help': '&#xea09;',
			'plus': '&#xea0a;',
			'add': '&#xea0a;',
			'minus': '&#xea0b;',
			'subtract': '&#xea0b;',
			'info': '&#xea0c;',
			'information': '&#xea0c;',
			'cancel-circle': '&#xea0d;',
			'close': '&#xea0d;',
			'blocked': '&#xea0e;',
			'forbidden': '&#xea0e;',
			'cross': '&#xea0f;',
			'cancel': '&#xea0f;',
			'checkmark': '&#xea10;',
			'tick': '&#xea10;',
			'enter': '&#xea13;',
			'signin': '&#xea13;',
			'exit': '&#xea14;',
			'signout': '&#xea14;',
			'volume-high': '&#xea26;',
			'volume': '&#xea26;',
			'volume-medium': '&#xea27;',
			'volume2': '&#xea27;',
			'volume-low': '&#xea28;',
			'volume3': '&#xea28;',
			'volume-mute': '&#xea29;',
			'volume4': '&#xea29;',
			'volume-mute2': '&#xea2a;',
			'volume5': '&#xea2a;',
			'volume-increase': '&#xea2b;',
			'volume6': '&#xea2b;',
			'volume-decrease': '&#xea2c;',
			'volume7': '&#xea2c;',
			'loop': '&#xea2d;',
			'repeat': '&#xea2d;',
			'loop2': '&#xea2e;',
			'repeat2': '&#xea2e;',
			'infinite': '&#xea2f;',
			'shuffle': '&#xea30;',
			'random': '&#xea30;',
			'sort-alpha-asc': '&#xea48;',
			'arrange': '&#xea48;',
			'sort-alpha-desc': '&#xea49;',
			'arrange2': '&#xea49;',
			'sort-numeric-asc': '&#xea4a;',
			'arrange3': '&#xea4a;',
			'sort-numberic-desc': '&#xea4b;',
			'arrange4': '&#xea4b;',
			'sort-amount-asc': '&#xea4c;',
			'arrange5': '&#xea4c;',
			'sort-amount-desc': '&#xea4d;',
			'arrange6': '&#xea4d;',
			'command': '&#xea4e;',
			'cmd': '&#xea4e;',
			'shift': '&#xea4f;',
			'ctrl': '&#xea50;',
			'control': '&#xea50;',
			'opt': '&#xea51;',
			'option': '&#xea51;',
			'checkbox-checked': '&#xea52;',
			'checkbox': '&#xea52;',
			'checkbox-unchecked': '&#xea53;',
			'checkbox2': '&#xea53;',
			'radio-checked': '&#xea54;',
			'radio-button': '&#xea54;',
			'radio-checked2': '&#xea55;',
			'radio-button2': '&#xea55;',
			'radio-unchecked': '&#xea56;',
			'radio-button3': '&#xea56;',
			'crop': '&#xea57;',
			'resize': '&#xea57;',
			'filter': '&#xea5b;',
			'funnel': '&#xea5b;',
			'share': '&#xea7d;',
			'out': '&#xea7d;',
			'new-tab': '&#xea7e;',
			'out2': '&#xea7e;',
			'share2': '&#xea82;',
			'social': '&#xea82;',
			'mail2': '&#xea83;',
			'contact2': '&#xea83;',
			'mail5': '&#xea86;',
			'contact5': '&#xea86;',
			'google': '&#xea87;',
			'brand': '&#xea87;',
			'google-plus': '&#xea88;',
			'brand2': '&#xea88;',
			'google-plus2': '&#xea89;',
			'brand3': '&#xea89;',
			'google-plus3': '&#xea8a;',
			'brand4': '&#xea8a;',
			'google-drive': '&#xea8b;',
			'brand5': '&#xea8b;',
			'facebook': '&#xea8c;',
			'brand6': '&#xea8c;',
			'facebook2': '&#xea8d;',
			'brand7': '&#xea8d;',
			'facebook3': '&#xea8e;',
			'brand8': '&#xea8e;',
			'instagram': '&#xea90;',
			'brand10': '&#xea90;',
			'twitter': '&#xea91;',
			'brand11': '&#xea91;',
			'twitter2': '&#xea92;',
			'brand12': '&#xea92;',
			'twitter3': '&#xea93;',
			'brand13': '&#xea93;',
			'feed2': '&#xea94;',
			'rss': '&#xea94;',
			'feed3': '&#xea95;',
			'rss2': '&#xea95;',
			'feed4': '&#xea96;',
			'rss3': '&#xea96;',
			'youtube': '&#xea97;',
			'brand14': '&#xea97;',
			'youtube2': '&#xea98;',
			'brand15': '&#xea98;',
			'youtube3': '&#xea99;',
			'brand16': '&#xea99;',
			'youtube4': '&#xea9a;',
			'brand17': '&#xea9a;',
			'flickr': '&#xeaa0;',
			'brand23': '&#xeaa0;',
			'flickr2': '&#xeaa1;',
			'brand24': '&#xeaa1;',
			'flickr3': '&#xeaa2;',
			'brand25': '&#xeaa2;',
			'flickr4': '&#xeaa3;',
			'brand26': '&#xeaa3;',
			'picassa': '&#xeaa4;',
			'brand27': '&#xeaa4;',
			'picassa2': '&#xeaa5;',
			'brand28': '&#xeaa5;',
			'dropbox': '&#xeaaf;',
			'brand38': '&#xeaaf;',
			'onedrive': '&#xeab0;',
			'brand39': '&#xeab0;',
			'blogger': '&#xeab9;',
			'brand48': '&#xeab9;',
			'blogger2': '&#xeaba;',
			'brand49': '&#xeaba;',
			'tumblr': '&#xeabb;',
			'brand50': '&#xeabb;',
			'tumblr2': '&#xeabc;',
			'brand51': '&#xeabc;',
			'yahoo': '&#xeabd;',
			'brand52': '&#xeabd;',
			'tux': '&#xeabe;',
			'brand53': '&#xeabe;',
			'apple': '&#xeabf;',
			'brand54': '&#xeabf;',
			'finder': '&#xeac0;',
			'brand55': '&#xeac0;',
			'android': '&#xeac1;',
			'brand56': '&#xeac1;',
			'windows': '&#xeac2;',
			'brand57': '&#xeac2;',
			'windows8': '&#xeac3;',
			'brand58': '&#xeac3;',
			'linkedin': '&#xeac8;',
			'brand63': '&#xeac8;',
			'linkedin2': '&#xeac9;',
			'brand64': '&#xeac9;',
			'pinterest': '&#xead0;',
			'brand71': '&#xead0;',
			'pinterest2': '&#xead1;',
			'brand72': '&#xead1;',
			'file-pdf': '&#xeada;',
			'file10': '&#xeada;',
			'file-word': '&#xeadc;',
			'file12': '&#xeadc;',
			'file-excel': '&#xeadd;',
			'file13': '&#xeadd;',
			'codepen': '&#xeae4;',
			'brand81': '&#xeae4;',
			'chrome': '&#xeae5;',
			'browser': '&#xeae5;',
			'firefox': '&#xeae6;',
			'browser2': '&#xeae6;',
			'IE': '&#xeae7;',
			'browser3': '&#xeae7;',
			'opera': '&#xeae8;',
			'browser4': '&#xeae8;',
			'safari': '&#xeae9;',
			'browser5': '&#xeae9;',
			'0': 0
		};
		delete icons['0'];
		window.icomoonLiga = function (els) {
			var classes,
				el,
				i,
				innerHTML,
				key;
			els = els || document.getElementsByTagName('*');
			if (!els.length) {
				els = [els];
			}
			for (i = 0; ; i += 1) {
				el = els[i];
				if (!el) {
					break;
				}
				classes = el.className;
				if (/icon_/.test(classes)) {
					innerHTML = el.innerHTML;
					if (innerHTML && innerHTML.length > 1) {
						for (key in icons) {
							if (icons.hasOwnProperty(key)) {
								innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
							}
						}
						el.innerHTML = innerHTML;
					}
				}
			}
		};
		window.icomoonLiga();
	}
}());